name: API Tests  # Name of the workflow

on:  
  push:  # Runs on every push to the repository
  pull_request:  # Runs on pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # The machine where tests will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Fetches latest code from repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"  # Ensure you use the correct version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest requests sqlalchemy psycopg2

      - name: Start FastAPI server
        run: uvicorn apiserver:app --host 0.0.0.0 --port 8000 &  # Adjust if needed
        env:
          PYTHONUNBUFFERED: 1  # Ensures logs are displayed in real-time

      - name: Wait for server to start
        run: sleep 5  # Give the server time to start

      - name: Run API Tests
        run: pytest testAutomation.py --html=report.html
