name: Run API Tests

on:  
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch
  workflow_dispatch:  # Allows manual execution of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Use the latest Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          uvicorn apiserver:app --host 127.0.0.1 --port 8000 --reload &
          sleep 5  # Wait for server to start

      - name: Run API Tests with Pytest
        run: pytest testAutomation.py --maxfail=1 --disable-warnings -v
